### ISSUE TITLE
Unit tests are failing

### ISSUE THREAD

**Issue by vkhazin** [vkhazin/mortgage-rates-service#3]
```
  Tests app
[INFO] Parsing
[INFO] Scraping
[INFO] Filtering
[INFO] Responding
    1) verifies get
    2) verifies post


  0 passing (1s)
  2 failing

  1) Tests app
       verifies get:
     Uncaught AssertionError: undefined must be a string
      at Object.isString (node_modules/unit.js/src/assertions.js:343:20)
      at new StringAsserter (node_modules/unit.js/src/asserters/string.js:68:14)
      at UnitJS.module.exports.(anonymous function) [as string] (node_modules/unit.js/src/asserters.js:27:14)
      at Test.<anonymous> (tests/test.js:12:14)
      at Test.assert (node_modules/supertest/lib/test.js:179:6)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1659:8)
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)

  2) Tests app
       verifies post:
     Uncaught AssertionError: undefined must be a string
      at Object.isString (node_modules/unit.js/src/assertions.js:343:20)
      at new StringAsserter (node_modules/unit.js/src/asserters/string.js:68:14)
      at UnitJS.module.exports.(anonymous function) [as string] (node_modules/unit.js/src/asserters.js:27:14)
      at Test.<anonymous> (tests/test.js:19:14)
      at Test.assert (node_modules/supertest/lib/test.js:179:6)
      at Server.assert (node_modules/supertest/lib/test.js:131:12)
      at emitCloseNT (net.js:1659:8)
      at _combinedTickCallback (internal/process/next_tick.js:135:11)
      at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by vkhazin** [comment]
resolved
